### ISSUE TITLE
Extension makes toast error message looks strange on application details page

### ISSUE THREAD

**Issue by alexmt** [argoproj-labs/rollout-extension#21]
Looks like extension loads old toast component CSS styles. See for more information: https://github.com/argoproj/argo-cd/issues/10733

**Comment by Marvin9** [comment]
I will update this repo UI to point new rollout UI after fix - https://github.com/argoproj/argo-rollouts/pull/3212. That will probably remove the override

**Comment by ashutosh16** [comment]
@Marvin9  I have upgraded the extension to use the latest argo rollout-ui, could you please review the [PR](https://github.com/argoproj-labs/rollout-extension/pull/66). The latest argo-rollout includes a new feature to display the [analysis modal] (https://github.com/argoproj/argo-rollouts/pull/3174). I have attempted to integrate the analysis modal into the rollout extension.

**Comment by alexmt** [comment]
Upgraded to v0.3.3 but still see the issue. Notifications colors are changing to red even with the new version

**Comment by Marvin9** [comment]
It seems like v0.3.3 doesn't include the build for the PR I fixed this issue for - https://github.com/argoproj-labs/rollout-extension/releases

This one should fix - https://github.com/argoproj-labs/rollout-extension/releases/tag/v0.3.4 but I don't know why it didn't show up as new release

**Comment by alexmt** [comment]
v0.3.4 release fixed it! thank you!
