### ISSUE TITLE
Extension UI "More" tab not appearing after opening another resource's details view

### ISSUE THREAD

**Issue by omarfakhreddine** [argoproj-labs/rollout-extension#31]
This issue may be similar to #1, #5  and some others.

Browser: `Brave Browser 1.45.123` (tested on Chrome as well, version 107.0.5304.110 (Official Build) (x86_64))
ArgoCD version: `v2.4.14+029be59.dirty`
Argo Rollouts version: `v1.3.1` (using rollouts helm chart `v2.21.1`)
Argo Extension Controller version: `v0.2.1`
Argo Rollout Extension version: `v0.3.0`

Rollouts extension installed by adding the file source (https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.0/extension.tar) to our argocd helm chart values file under `server.extensions.contents.url`

Description of issue:
When clicking on the rollout resource the first time after refreshing or opening the application in the argoCD UI, the `More` tab shows up. However, after opening another resource (by clicking on the tile in the application page) and returning the the rollout resource view, the `More` tab doesn't show up.

Replication steps:

1. Open the rollout resource's detailed view
2. Return back to the application's tile view by clicking on the empty space outside of the details page that pops out from the right side of the screen
3. Open another resource's detailed view
4. Return back to the application's tile view by clicking on the empty space outside of the details page that pops out from the right side of the screen
5. Open the rollout resource's detailed view, the `More` tab won't appear next to `Logs`

Errors that pop up in the browser console during step 3 above:
```
GET https://argocd.sbx.scheduleengine.net/extensions/resources/argoproj.io/AnalysisTemplate/ui/extensions.js net::ERR_ABORTED 404

Refused to execute script from 'https://argocd.sbx.scheduleengine.net/extensions/resources/argoproj.io/AnalysisTemplate/ui/extensions.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
![image](https://user-images.githubusercontent.com/66579938/203639955-ce377970-b7a6-45e0-8f9f-1330df70ddc7.png)

Temporary solution:
Refreshing the current application page or reopening it from the `Applications` page and opening the rollout resource detailed view page before opening other resources.

Please let me know if more details are needed to help with this.

**Comment by zachaller** [comment]
This is possibly fixed upstream on master by https://github.com/argoproj/argo-rollouts/pull/2303

**Comment by omarfakhreddine** [comment]
Will there be a release soon that includes this PR?

**Comment by zachaller** [comment]
Yea there should be a release Jan-Feb
