### ISSUE TITLE
Seeing this issue when viewing the 0.3.0 rollout extenion in ArgoCD 2.6.6

### ISSUE THREAD

**Issue by winterhalder** [argoproj-labs/rollout-extension#45]
Using ArgoCD rollout extension 0.3.0

I *do* see the extension when I go to the More page for the rollout.

But once I've been on the page for a minute or so this happens. It also happens if I attempt to exit the view, or trigger the full promotion.

---

Something went wrong!

Consider submitting an issue [here](https://github.com/argoproj/argo-cd/issues/new?labels=bug&template=bug_report.md).

Stacktrace:

TypeError: Cannot read properties of undefined (reading 'name')
    at anchor (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:1681800)
    at Jr (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:807467)
    at ya (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:853372)
    at pl (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:846148)
    at dl (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:846073)
    at il (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:843103)
    at https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:794882
    at t.unstable_runWithPriority (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:869930)
    at Uo (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:794591)
    at qo (https://argocd.bitheads.com/main.c87b5e37f99fc2a30256.js:2:794827)

Now to be fair - it's prompting me to issue a defect with argocd itself - but this seems more like an error with the extension???  (We've certainly never seen anything like this in ArgoCD until we started using the rollouts extension).

Thoughts?

**Comment by winterhalder** [comment]
For the more visually inclined...
<img width="1001" alt="2023-05-03_18-06-59" src="https://user-images.githubusercontent.com/3590310/236060599-03baf769-3a45-4f8f-9838-071f8702bcb1.png">

**Comment by winterhalder** [comment]
Similar issue in argocd issues list - https://github.com/argoproj/argo-cd/issues/12671

**Comment by huynhsontung** [comment]
I had this same issue. The problem went away after I restarted all the Deployments. Either that or it just went away by itself after 2 days.

**Comment by winterhalder** [comment]
Could the fix have been in 2.7.3?  Certainly all my deployments restart fairly regularly...  I haven't found 2.7.3 yet though...

**Comment by winterhalder** [comment]
Hmm - I've upgraded to 2.7.3 - and restarted the relevant Rollouts (that's what you meant by Deployments, right?) - and am still seeing the issue.

It still isn't happening for you anymore @huynhsontung ?

**Comment by huynhsontung** [comment]
@winterhalder My bad. I meant ArgoCD Deployments like repo server, redis, application controller. Maybe clear your browser cache as well for good measure. So far this problem has gone away from my end.

**Comment by winterhalder** [comment]
Well - I restarted all the argo deployments - and cleared my browser cache...  and then went further and tried using a browser I never use for dev stuff (Edge) --  and I still have the issue.

I did a bit more experimentation though - and it appears the issue is related to my preferred view - which is the "Pods" view - not the default Tree view.

If I view the "More" tab a Deployment from the Tree view page - things work fine. But if I do it from the Pods view - I get the crash when I try to navigate around it...  (in the video, you'll also note that I got the crash when attempting to navigate from Tree -> Pods -- but that's probably because I had previously crashed in Pods and it was remembering it?

Anyway - good to know that the alternate view works more reliably - but it would be even better to get this fixed! 

So @huynhsontung - any chance you still have this issue from the Pods view? Am I the only one seeing this? :)

https://github.com/argoproj-labs/rollout-extension/assets/3590310/34864c2c-af09-4a68-8ef6-1fd68024d501

**Comment by huynhsontung** [comment]
@winterhalder Confirmed I encountered the same issue when using the Pods view. Still not exactly sure what's the root cause for this. Now that I have a reliable method to cause the error, I will try to investigate.

**Comment by winterhalder** [comment]
Update - the new 0.3.1 release of the rollouts extension (potentially combined with Argo 2.7.11) seems to fix this! Woot!

(Thank-you kind strangers!)

**Comment by winterhalder** [comment]
D'oh - I kind-of spoke too soon.  It's no longer crashing - but we no longer see the list of pods either!

https://app.screencast.com/i5pJV7yhTBIM3

**Comment by huynhsontung** [comment]
I noticed the same thing. At least it doesn't crash anymore. The pod info is still available in other parts of the UI.

**Comment by winterhalder** [comment]
Yeah - but it really hurts one's understanding of the progression not to see the pods of each version...
