### ISSUE TITLE
The 0.3.3 install manifest refers to 0.3.1 (instead of 0.3.3)

### ISSUE THREAD

**Issue by winterhalder** [argoproj-labs/rollout-extension#61]
The reference in this file is incorrect:

https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.3.3/manifests/install.yaml

`spec:
  sources:
  - web:
      url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.1/extension.tar`

As you can see - it refers to the 0.3.1 tar file - but it should be the 0.3.3 tar file.

**Comment by winterhalder** [comment]
Note that as a work-around, you can edit the resource live in the cluster:

kubectl edit ArgoCDExtension/argo-rollouts

I believe you need to restart a few servers after the change.

**Comment by beyondbill** [comment]
Fixed by https://github.com/argoproj-labs/rollout-extension/pull/69 but the commit is not in v0.3.3 release. I get around it by using [](https://raw.githubusercontent.com/argoproj-labs/rollout-extension/master/manifests/install.yaml)
